module.exports = {
  plugins: [
    // require('postcss-normalize')(),
    require('postcss-import')(),
    require('postcss-custom-properties')(),
    require('postcss-calc')(),
    require('postcss-image-set-polyfill')(),
    require('postcss-nesting')(),
    require('postcss-custom-media')(),
    require('postcss-media-minmax')(),
    require('postcss-custom-selectors')(),
    require('postcss-attribute-case-insensitive')(),
    require('postcss-color-hwb')(),
    require('postcss-color-hsl')(),
    require('postcss-color-rgb')(),
    require('postcss-color-gray')(),
    require('postcss-color-hex-alpha')(),
    require('postcss-color-function')(),
    require('postcss-font-family-system-ui')(),
    require('postcss-font-variant')(),
    require('pleeease-filters')(),
    require('postcss-initial')(),
    require('pixrem')(),
    require('postcss-pseudoelements')(),
    require('postcss-selector-matches')(),
    require('postcss-selector-not')(),
    require('postcss-pseudo-class-any-link')(),
    require('postcss-color-rgba-fallback')(),
    require('postcss-replace-overflow-wrap')(),
    require('postcss-typescale')(),
    require('postcss-grid-fluid')(),
    require('postcss-grid-system')(),
    require('postcss-button')()
  ]
}