module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-custom-properties': {},
    'postcss-calc': {},
    'postcss-image-set-polyfill': {},
    'postcss-nesting': {},
    'postcss-custom-media': {},
    'postcss-media-minmax': {},
    'postcss-custom-selectors': {},
    'postcss-attribute-case-insensitive': {},
    'postcss-color-hwb': {},
    'postcss-color-hsl': {},
    'postcss-color-rgb': {},
    'postcss-color-gray': {},
    'postcss-color-hex-alpha': {},
    'postcss-color-function': {},
    'postcss-font-family-system-ui': {},
    'postcss-font-variant': {},
    'pleeease-filters': {},
    'postcss-initial': {},
    'pixrem': {},
    'postcss-pseudoelements': {},
    'postcss-selector-matches': {},
    'postcss-selector-not': {},
    'postcss-pseudo-class-any-link': {},
    'postcss-color-rgba-fallback': {},
    'postcss-replace-overflow-wrap': {},
    'postcss-typescale': {},
    'postcss-grid-system': {},
    'postcss-grid-fluid': {},
    'postcss-button': {},
    'postcss-inline-svg': {},
    'autoprefixer': {}
  }
}